const npcAIPattern = {
    basicPattern: [
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    loopPattern: [
        { actionTime: 0, action: "move", value: [10, 5, 0] },
        { actionTime: 35, action: "setRotation", value: "pc" },
        { actionTime: 50, action: "blaster", value: "pc" },
        { actionTime: 70, action: "blaster", value: "pc" },
        { actionTime: 110, action: "move", value: [-10, -5, 0] },
        { actionTime: 125, action: "setRotation", value: "pc" },
        { actionTime: 140, action: "blaster", value: "pc" },
        { actionTime: 160, action: "blaster", value: "pc" },
        { actionTime: 180, action: "setPatternTime", value: 0 },
    ],
    randomMove: [
        { actionTime: 0, action: "randomMoveTo", value: [-20, 20, -10, 10, 150, 200] },
        { actionTime: 50, action: "setRotation", value: "pc" },
        { actionTime: 70, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 100, action: "blaster", value: "front" },
        { actionTime: 100, action: "randomMoveTo", value: [-20, 20, -10, 10, 150, 200] },
        { actionTime: 120, action: "setRotation", value: "pc" },
        { actionTime: 140, action: "blaster", value: "front" },
        { actionTime: 160, action: "blaster", value: "front" },
        { actionTime: 180, action: "blaster", value: "front" },
        { actionTime: 180, action: "setPatternTime", value: 0 },
    ],
    charge: [
        { actionTime: 10, action: "setRotation", value: "pc" },
        { actionTime: 25, action: "setDefaultSpeed", value: [0, 0, 1] },
        { actionTime: 30, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 50, action: "setRotation", value: "pc" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 70, action: "setRotation", value: "pc" },
    ],
    droneIntroPattern: [ // need time 200
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    bomberIntroPattern: [ // need time 500
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    fighterIntroPattern: [ // need time 250
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    destroyerIntroPattern: [ // need time 300
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    cruiserIntroPattern: [ // need time 600
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    asteroidIntroPattern: [
        { actionTime: 0, action: "setDefaultSpeed", value: [0, 0, 10] },
    ],

    droneRandomMove1Q: [
        { actionTime: 0, action: "randomMoveTo", value: [5, 25, 5, 15, 150, 180] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 0, action: "randomMoveTo", value: [5, 25, 5, 15, 150, 180] },
        { actionTime: 120, action: "setRotation", value: "pc" },
        { actionTime: 140, action: "blaster", value: "front" },
        { actionTime: 160, action: "blaster", value: "front" },
        { actionTime: 180, action: "blaster", value: "front" },
        { actionTime: 180, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove2Q: [
        { actionTime: 0, action: "randomMoveTo", value: [-25, -5, 5, 15, 150, 180] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 0, action: "randomMoveTo", value: [-25, -5, 5, 15, 150, 180] },
        { actionTime: 120, action: "setRotation", value: "pc" },
        { actionTime: 140, action: "blaster", value: "front" },
        { actionTime: 160, action: "blaster", value: "front" },
        { actionTime: 180, action: "blaster", value: "front" },
        { actionTime: 180, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove3Q: [
        { actionTime: 0, action: "randomMoveTo", value: [5, 25, -15, -5, 150, 180] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 0, action: "randomMoveTo", value: [5, 25, -15, -5, 150, 180] },
        { actionTime: 120, action: "setRotation", value: "pc" },
        { actionTime: 140, action: "blaster", value: "front" },
        { actionTime: 160, action: "blaster", value: "front" },
        { actionTime: 180, action: "blaster", value: "front" },
        { actionTime: 180, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove4Q: [
        { actionTime: 0, action: "randomMoveTo", value: [-25, -5, -15, -5, 150, 180] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 0, action: "randomMoveTo", value: [-25, -5, -15, -5, 150, 180] },
        { actionTime: 120, action: "setRotation", value: "pc" },
        { actionTime: 140, action: "blaster", value: "front" },
        { actionTime: 160, action: "blaster", value: "front" },
        { actionTime: 180, action: "blaster", value: "front" },
        { actionTime: 180, action: "setPatternTime", value: 0 },
    ],

    bomberDefaultMoveZ: [
        { actionTime: 0, action: "setDefaultSpeed", value: [0, 0, 0.5] },
    ],
    bomberBlastLoop: [
        { actionTime: 10, action: "blaster", value: "pc" },
        { actionTime: 60, action: "setPatternTime", value: 0 },
    ],

    fighterRandomMove1H: [
        { actionTime: 0, action: "randomMoveTo", value: [35, 5, -10, 10, 150, 180] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 0, action: "randomMoveTo", value: [35, 5, -10, 10, 150, 180] },
        { actionTime: 120, action: "setRotation", value: "pc" },
        { actionTime: 140, action: "blaster", value: "front" },
        { actionTime: 160, action: "blaster", value: "front" },
        { actionTime: 180, action: "blaster", value: "front" },
        { actionTime: 180, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove2H: [
        { actionTime: 0, action: "randomMoveTo", value: [-35, -5, -10, 10, 150, 180] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 0, action: "randomMoveTo", value: [-35, -5, -10, 10, 150, 180] },
        { actionTime: 120, action: "setRotation", value: "pc" },
        { actionTime: 140, action: "blaster", value: "front" },
        { actionTime: 160, action: "blaster", value: "front" },
        { actionTime: 180, action: "blaster", value: "front" },
        { actionTime: 180, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove1Q: [
        { actionTime: 0, action: "randomMoveTo", value: [5, 25, 5, 15, 150, 180] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 0, action: "randomMoveTo", value: [5, 25, 5, 15, 150, 180] },
        { actionTime: 120, action: "setRotation", value: "pc" },
        { actionTime: 140, action: "blaster", value: "front" },
        { actionTime: 160, action: "blaster", value: "front" },
        { actionTime: 180, action: "blaster", value: "front" },
        { actionTime: 180, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove2Q: [
        { actionTime: 0, action: "randomMoveTo", value: [-25, -5, 5, 15, 150, 180] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 0, action: "randomMoveTo", value: [-25, -5, 5, 15, 150, 180] },
        { actionTime: 120, action: "setRotation", value: "pc" },
        { actionTime: 140, action: "blaster", value: "front" },
        { actionTime: 160, action: "blaster", value: "front" },
        { actionTime: 180, action: "blaster", value: "front" },
        { actionTime: 180, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove3Q: [
        { actionTime: 0, action: "randomMoveTo", value: [5, 25, -15, -5, 150, 180] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 0, action: "randomMoveTo", value: [5, 25, -15, -5, 150, 180] },
        { actionTime: 120, action: "setRotation", value: "pc" },
        { actionTime: 140, action: "blaster", value: "front" },
        { actionTime: 160, action: "blaster", value: "front" },
        { actionTime: 180, action: "blaster", value: "front" },
        { actionTime: 180, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove4Q: [
        { actionTime: 0, action: "randomMoveTo", value: [-25, -5, -15, -5, 150, 180] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 0, action: "randomMoveTo", value: [-25, -5, -15, -5, 150, 180] },
        { actionTime: 120, action: "setRotation", value: "pc" },
        { actionTime: 140, action: "blaster", value: "front" },
        { actionTime: 160, action: "blaster", value: "front" },
        { actionTime: 180, action: "blaster", value: "front" },
        { actionTime: 180, action: "setPatternTime", value: 0 },
    ],

    destroyerRandomMove2H: [
        { actionTime: 0, action: "blaster", value: "front" },
        { actionTime: 10, action: "blaster", value: "front" },
        { actionTime: 15, action: "setRotation", value: "pc" },
        { actionTime: 20, action: "blaster", value: "front" },
        { actionTime: 30, action: "blaster", value: "front" },
        { actionTime: 35, action: "randomMoveTo", value: [-35, -5, -10, 10, 150, 180] },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 45, action: "setRotation", value: "pc" },
        { actionTime: 50, action: "blaster", value: "front" },
        { actionTime: 60, action: "setPatternTime", value: 0 },
    ],

};

export default npcAIPattern;