const npcAIPattern = {
    basicPattern: [
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    loopPattern: [
        { actionTime: 0, action: "move", value: [10, 5, 0] },
        { actionTime: 35, action: "setRotation", value: "pc" },
        { actionTime: 50, action: "blaster", value: "pc" },
        { actionTime: 70, action: "blaster", value: "pc" },
        { actionTime: 110, action: "move", value: [-10, -5, 0] },
        { actionTime: 125, action: "setRotation", value: "pc" },
        { actionTime: 140, action: "blaster", value: "pc" },
        { actionTime: 160, action: "blaster", value: "pc" },
        { actionTime: 180, action: "setPatternTime", value: 0 },
    ],
    randomMove: [
        { actionTime: 0, action: "randomMoveTo", value: [-20, 20, -10, 10, 130, 160] },
        { actionTime: 50, action: "setRotation", value: "pc" },
        { actionTime: 70, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 100, action: "blaster", value: "front" },
        { actionTime: 105, action: "setPatternTime", value: 0 },
    ],
    charge: [
        { actionTime: 10, action: "setRotation", value: "pc" },
        { actionTime: 25, action: "setDefaultSpeed", value: [0, 0, 1] },
        { actionTime: 30, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 50, action: "setRotation", value: "pc" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 70, action: "setRotation", value: "pc" },
        { actionTime: 80, action: "setRotation", value: "pc" },
        { actionTime: 90, action: "blaster", value: "front" },
        { actionTime: 100, action: "setRotation", value: "pc" },
        { actionTime: 110, action: "blaster", value: "front" },
        { actionTime: 120, action: "setRotation", value: "pc" },
        { actionTime: 130, action: "setRotation", value: "pc" },
        { actionTime: 140, action: "blaster", value: "front" },
        { actionTime: 150, action: "setRotation", value: "pc" },
        { actionTime: 160, action: "blaster", value: "front" },
        { actionTime: 170, action: "setRotation", value: "pc" },
        { actionTime: 180, action: "setRotation", value: "pc" },
    ],
    droneIntroPattern: [ // need time 200
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    bomberIntroPattern: [ // need time 500
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    fighterIntroPattern: [ // need time 250
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    destroyerIntroPattern: [ // need time 300
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    cruiserIntroPattern: [ // need time 600
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    asteroidIntroPattern: [],
    bossIntroPattern: [ // need time 500
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],

    droneRandomMove1H: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, -15, 15, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove2H: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, 15, 15, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove1Q: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, 5, 15, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove2Q: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, 5, 15, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove3Q: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, -15, -5, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove4Q: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, -15, -5, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove1hQ: [
        { actionTime: 0, action: "randomMoveTo", value: [15, 30, 5, 15, 130, 160]},
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove2hQ: [
        { actionTime: 0, action: "randomMoveTo", value: [0, 15, 5, 15, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove3hQ: [
        { actionTime: 0, action: "randomMoveTo", value: [-15, 0, 5, 15, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove4hQ: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -15, 5, 15, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove5hQ: [
        { actionTime: 0, action: "randomMoveTo", value: [15, 30, -15, -5, 130, 160]},
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove6hQ: [
        { actionTime: 0, action: "randomMoveTo", value: [0, 15, -15, -5, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove7hQ: [
        { actionTime: 0, action: "randomMoveTo", value: [-15, 0, -15, -5, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove8hQ: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -15, -15, -5, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    // Drone Front Line
    droneRandomMove1hQF: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, 5, 15, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove2QF: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, 5, 15, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove3QF: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, -15, -5, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove4QF: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, -15, -5, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove1hQF: [
        { actionTime: 0, action: "randomMoveTo", value: [15, 30, 5, 15, 130, 140]},
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove2hQF: [
        { actionTime: 0, action: "randomMoveTo", value: [0, 15, 5, 15, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove3hQF: [
        { actionTime: 0, action: "randomMoveTo", value: [-15, 0, 5, 15, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove4hQF: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -15, 5, 15, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove5hQF: [
        { actionTime: 0, action: "randomMoveTo", value: [15, 30, -15, -5, 130, 140]},
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove6hQF: [
        { actionTime: 0, action: "randomMoveTo", value: [0, 15, -15, -5, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove7hQF: [
        { actionTime: 0, action: "randomMoveTo", value: [-15, 0, -15, -5, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove8hQF: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -15, -15, -5, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    // Drone Rear Line
    droneRandomMove1QR: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, 5, 15, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove2QR: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, 5, 15, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove3QR: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, -15, -5, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove4QR: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, -15, -5, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove1hQR: [
        { actionTime: 0, action: "randomMoveTo", value: [15, 30, 5, 15, 150, 160]},
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove2hQR: [
        { actionTime: 0, action: "randomMoveTo", value: [0, 15, 5, 15, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove3hQR: [
        { actionTime: 0, action: "randomMoveTo", value: [-15, 0, 5, 15, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove4hQR: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -15, 5, 15, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove5hQR: [
        { actionTime: 0, action: "randomMoveTo", value: [15, 30, -15, -5, 150, 160]},
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove6hQR: [
        { actionTime: 0, action: "randomMoveTo", value: [0, 15, -15, -5, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove7hQR: [
        { actionTime: 0, action: "randomMoveTo", value: [-15, 0, -15, -5, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove8hQR: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -15, -15, -5, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    // Drone Sortie
    droneSortieFromR: [
        { actionTime: 10, action: "move", value: [30, -10, 50] },
    ],
    droneSortieFromRAfter:
    [
        { actionTime: 10, action: "moveTo", value: [0, -5, 150] },
        { actionTime: 20, action: "setPatternTime", value: 0 },
    ],
    droneSortieFromL: [
        { actionTime: 10, action: "move", value: [-30, -10, 50] },
    ],
    droneSortieFromLAfter:
    [
        { actionTime: 10, action: "moveTo", value: [0, -5, 150] },
        { actionTime: 20, action: "setPatternTime", value: 0 },
    ],
    
    // Bomber
    bomberDefaultMoveZ: [
        { actionTime: 0, action: "setDefaultSpeed", value: [0, 0, 0.5] },
    ],
    bomberBlastLoop: [
        { actionTime: 10, action: "blaster", value: "pc" },
        { actionTime: 60, action: "setPatternTime", value: 0 },
    ],

    fighterRandomMove1H: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, -10, 10, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove2H: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, -10, 10, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove1Q: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, 5, 15, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove2Q: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, 5, 15, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove3Q: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, -15, -5, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove4Q: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10 -15, -5, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove1HR: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, -10, 10, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove2HR: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, -10, 10, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove1QR: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, 5, 15, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove2QR: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, 5, 15, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove3QR: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, -15, -5, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove4QR: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10 -15, -5, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],

    // Destroyer
    destroyerRandomMove1H: [
        { actionTime: 0, action: "blaster", value: "front" },
        { actionTime: 10, action: "blaster", value: "front" },
        { actionTime: 15, action: "setRotation", value: "pc" },
        { actionTime: 20, action: "blaster", value: "front" },
        { actionTime: 30, action: "blaster", value: "front" },
        { actionTime: 35, action: "randomMoveTo", value: [5, 35, -10, 10, 130, 160] },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 45, action: "setRotation", value: "pc" },
        { actionTime: 50, action: "blaster", value: "front" },
        { actionTime: 60, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove2H: [
        { actionTime: 0, action: "blaster", value: "front" },
        { actionTime: 10, action: "blaster", value: "front" },
        { actionTime: 15, action: "setRotation", value: "pc" },
        { actionTime: 20, action: "blaster", value: "front" },
        { actionTime: 30, action: "blaster", value: "front" },
        { actionTime: 35, action: "randomMoveTo", value: [-35, -5, -10, 10, 130, 160] },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 45, action: "setRotation", value: "pc" },
        { actionTime: 50, action: "blaster", value: "front" },
        { actionTime: 60, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove1Q: [
        { actionTime: 0, action: "randomMoveTo", value: [5, 35, 5, 15, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove2Q: [
        { actionTime: 0, action: "randomMoveTo", value: [-35, -5, 5, 15, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove3Q: [
        { actionTime: 0, action: "randomMoveTo", value: [5, 35, -15, -5, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove4Q: [
        { actionTime: 0, action: "randomMoveTo", value: [-35, -5 -15, -5, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    // Destroyer Front Line
    destroyerRandomMove1HF: [
        { actionTime: 0, action: "blaster", value: "front" },
        { actionTime: 10, action: "blaster", value: "front" },
        { actionTime: 15, action: "setRotation", value: "pc" },
        { actionTime: 20, action: "blaster", value: "front" },
        { actionTime: 30, action: "blaster", value: "front" },
        { actionTime: 35, action: "randomMoveTo", value: [5, 35, -10, 10, 130, 140] },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 45, action: "setRotation", value: "pc" },
        { actionTime: 50, action: "blaster", value: "front" },
        { actionTime: 60, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove2HF: [
        { actionTime: 0, action: "blaster", value: "front" },
        { actionTime: 10, action: "blaster", value: "front" },
        { actionTime: 15, action: "setRotation", value: "pc" },
        { actionTime: 20, action: "blaster", value: "front" },
        { actionTime: 30, action: "blaster", value: "front" },
        { actionTime: 35, action: "randomMoveTo", value: [-35, -5, -10, 10, 130, 140] },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 45, action: "setRotation", value: "pc" },
        { actionTime: 50, action: "blaster", value: "front" },
        { actionTime: 60, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove1QF: [
        { actionTime: 0, action: "randomMoveTo", value: [5, 35, 5, 15, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove2QF: [
        { actionTime: 0, action: "randomMoveTo", value: [-35, -5, 5, 15, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove3QF: [
        { actionTime: 0, action: "randomMoveTo", value: [5, 35, -15, -5, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove4QF: [
        { actionTime: 0, action: "randomMoveTo", value: [-35, -5 -15, -5, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    // Destroyer Rear Line
    destroyerRandomMove1HR: [
        { actionTime: 0, action: "blaster", value: "front" },
        { actionTime: 10, action: "blaster", value: "front" },
        { actionTime: 15, action: "setRotation", value: "pc" },
        { actionTime: 20, action: "blaster", value: "front" },
        { actionTime: 30, action: "blaster", value: "front" },
        { actionTime: 35, action: "randomMoveTo", value: [5, 35, -15, 15, 150, 160] },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 45, action: "setRotation", value: "pc" },
        { actionTime: 50, action: "blaster", value: "front" },
        { actionTime: 60, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove2HR: [
        { actionTime: 0, action: "blaster", value: "front" },
        { actionTime: 10, action: "blaster", value: "front" },
        { actionTime: 15, action: "setRotation", value: "pc" },
        { actionTime: 20, action: "blaster", value: "front" },
        { actionTime: 30, action: "blaster", value: "front" },
        { actionTime: 35, action: "randomMoveTo", value: [-35, -5, -15, 15, 150, 160] },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 45, action: "setRotation", value: "pc" },
        { actionTime: 50, action: "blaster", value: "front" },
        { actionTime: 60, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove1QR: [
        { actionTime: 0, action: "randomMoveTo", value: [5, 35, 5, 15, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove2QR: [
        { actionTime: 0, action: "randomMoveTo", value: [-35, -5, 5, 15, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove3QR: [
        { actionTime: 0, action: "randomMoveTo", value: [5, 35, -15, -5, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove4QR: [
        { actionTime: 0, action: "randomMoveTo", value: [-35, -5 -15, -5, 150, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],

    // Cruiser
    cruiserDefaultMoveZ: [
        { actionTime: 0, action: "setDefaultSpeed", value: [0, 0, 0.5] },
    ],
    cruiserBlastLoop: [
        { actionTime: 40, action: "blaster", value: "pc" },
        { actionTime: 50, action: "blaster", value: "pc" },
        { actionTime: 60, action: "blaster", value: "pc" },
        { actionTime: 120, action: "setPatternTime", value: 0 },
    ],

    // Boss
    bossFirstAttack: [
        { actionTime: 10, action: "blaster", value: "pc" },
        { actionTime: 30, action: "blaster", value: "pc" },
        { actionTime: 50, action: "blaster", value: "pc" },
        { actionTime: 70, action: "blaster", value: "pc" },
        { actionTime: 90, action: "blaster", value: "pc" },
        { actionTime: 120, action: "blaster", value: "pc" },
        { actionTime: 150, action: "blaster", value: "pc" },
        { actionTime: 250, action: "setPatternTime", value: 0 },
    ],
    bossLoop: [
        { actionTime: 0, action: "setRotation", value: "pc" },
        { actionTime: 10, action: "blaster", value: "pc" },
        { actionTime: 20, action: "blaster", value: "pc" },
        { actionTime: 30, action: "blaster", value: "pc" },
        { actionTime: 35, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "pc" },
        { actionTime: 50, action: "blaster", value: "pc" },
        { actionTime: 60, action: "blaster", value: "pc" },
        { actionTime: 60, action: "setRotation", value: [0, 0, 0] },
        { actionTime: 65, action: "randomMoveTo", value: [-5, 5, -5, 5, 190, 200] },
        { actionTime: 85, action: "setRotation", value: "pc" },
        { actionTime: 90, action: "blaster", value: "pc" },
        { actionTime: 100, action: "blaster", value: "pc" },
        { actionTime: 110, action: "blaster", value: "pc" },
        { actionTime: 115, action: "setRotation", value: "pc" },
        { actionTime: 120, action: "blaster", value: "pc" },
        { actionTime: 130, action: "blaster", value: "pc" },
        { actionTime: 140, action: "blaster", value: "pc" },
        { actionTime: 150, action: "setRotation", value: [0, 0, 0] },
        { actionTime: 180, action: "randomMoveTo", value: [-5, 5, -5, 5, 190, 200] },
        { actionTime: 240, action: "randomMoveTo", value: [-5, 5, -5, 5, 190, 200] },
        { actionTime: 300, action: "setPatternTime", value: 0 },
    ],
    bossFinalLoop: [
        { actionTime: 5, action: "setRotation", value: [0, 0, 0] },
        { actionTime: 10, action: "blaster", value: "pc" },
        { actionTime: 20, action: "blaster", value: "pc" },
        { actionTime: 30, action: "blaster", value: "pc" },
        { actionTime: 40, action: "blaster", value: "pc" },
        { actionTime: 50, action: "blaster", value: "pc" },
        { actionTime: 60, action: "setRotation", value: [0, 0, 0] },
        { actionTime: 60, action: "moveTo", value: [0, 0, 75] },
        { actionTime: 120, action: "blaster", value: "pc" },
        { actionTime: 130, action: "blaster", value: "pc" },
        { actionTime: 140, action: "blaster", value: "pc" },
        { actionTime: 150, action: "blaster", value: "pc" },
        { actionTime: 160, action: "blaster", value: "pc" },
        { actionTime: 170, action: "blaster", value: "pc" },
        { actionTime: 180, action: "blaster", value: "pc" },
        { actionTime: 190, action: "blaster", value: "pc" },
        { actionTime: 200, action: "blaster", value: "pc" },
        { actionTime: 210, action: "blaster", value: "pc" },
        { actionTime: 220, action: "blaster", value: "pc" },
        { actionTime: 230, action: "blaster", value: "pc" },
        { actionTime: 240, action: "blaster", value: "pc" },
        { actionTime: 250, action: "blaster", value: "pc" },
        { actionTime: 260, action: "blaster", value: "pc" },
        { actionTime: 280, action: "blaster", value: "pc" },
        { actionTime: 290, action: "blaster", value: "pc" },
        { actionTime: 300, action: "blaster", value: "pc" },
        { actionTime: 310, action: "blaster", value: "pc" },
        { actionTime: 320, action: "blaster", value: "pc" },
        { actionTime: 330, action: "randomMoveTo", value: [-15, 15, -5, 5, 80, 100] },
        { actionTime: 400, action: "setPatternTime", value: 0 },
    ],



    fighterRandomMove1HF: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, -10, 10, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove2HF: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, -10, 10, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove1QF: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, 5, 15, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove2QF: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, 5, 15, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove3QF: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, -15, -5, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove4QF: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10 -15, -5, 130, 140] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],


    
};

export default npcAIPattern;