const npcAIPattern = {
    basicPattern: [
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    loopPattern: [
        { actionTime: 0, action: "move", value: [10, 5, 0] },
        { actionTime: 35, action: "setRotation", value: "pc" },
        { actionTime: 50, action: "blaster", value: "pc" },
        { actionTime: 70, action: "blaster", value: "pc" },
        { actionTime: 110, action: "move", value: [-10, -5, 0] },
        { actionTime: 125, action: "setRotation", value: "pc" },
        { actionTime: 140, action: "blaster", value: "pc" },
        { actionTime: 160, action: "blaster", value: "pc" },
        { actionTime: 180, action: "setPatternTime", value: 0 },
    ],
    randomMove: [
        { actionTime: 0, action: "randomMoveTo", value: [-20, 20, -10, 10, 130, 160] },
        { actionTime: 50, action: "setRotation", value: "pc" },
        { actionTime: 70, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 100, action: "blaster", value: "front" },
        { actionTime: 105, action: "setPatternTime", value: 0 },
    ],
    charge: [
        { actionTime: 10, action: "setRotation", value: "pc" },
        { actionTime: 25, action: "setDefaultSpeed", value: [0, 0, 1] },
        { actionTime: 30, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 50, action: "setRotation", value: "pc" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 70, action: "setRotation", value: "pc" },
    ],
    droneIntroPattern: [ // need time 200
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    bomberIntroPattern: [ // need time 500
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    fighterIntroPattern: [ // need time 250
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    destroyerIntroPattern: [ // need time 300
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    cruiserIntroPattern: [ // need time 600
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],
    asteroidIntroPattern: [],
    bossIntroPattern: [ // need time 500
        { actionTime: 0, action: "move", value: [0, 0, -500] },
    ],

    droneRandomMove1Q: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, 5, 15, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove2Q: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, 5, 15, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove3Q: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, -15, -5, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    droneRandomMove4Q: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, -15, -5, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],

    bomberDefaultMoveZ: [
        { actionTime: 0, action: "setDefaultSpeed", value: [0, 0, 0.5] },
    ],
    bomberBlastLoop: [
        { actionTime: 10, action: "blaster", value: "pc" },
        { actionTime: 60, action: "setPatternTime", value: 0 },
    ],

    fighterRandomMove1H: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, -10, 10, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove2H: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, -10, 10, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove1Q: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, 5, 15, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove2Q: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10, 5, 15, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove3Q: [
        { actionTime: 0, action: "randomMoveTo", value: [10, 30, -15, -5, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],
    fighterRandomMove4Q: [
        { actionTime: 0, action: "randomMoveTo", value: [-30, -10 -15, -5, 130, 160] },
        { actionTime: 20, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 60, action: "blaster", value: "front" },
        { actionTime: 80, action: "blaster", value: "front" },
        { actionTime: 90, action: "setPatternTime", value: 0 },
    ],

    destroyerRandomMove2H: [
        { actionTime: 0, action: "blaster", value: "front" },
        { actionTime: 10, action: "blaster", value: "front" },
        { actionTime: 15, action: "setRotation", value: "pc" },
        { actionTime: 20, action: "blaster", value: "front" },
        { actionTime: 30, action: "blaster", value: "front" },
        { actionTime: 35, action: "randomMoveTo", value: [5, 35, -15, 15, 130, 160] },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 45, action: "setRotation", value: "pc" },
        { actionTime: 50, action: "blaster", value: "front" },
        { actionTime: 60, action: "setPatternTime", value: 0 },
    ],
    destroyerRandomMove2H: [
        { actionTime: 0, action: "blaster", value: "front" },
        { actionTime: 10, action: "blaster", value: "front" },
        { actionTime: 15, action: "setRotation", value: "pc" },
        { actionTime: 20, action: "blaster", value: "front" },
        { actionTime: 30, action: "blaster", value: "front" },
        { actionTime: 35, action: "randomMoveTo", value: [-35, -5, -15, 15, 130, 160] },
        { actionTime: 40, action: "blaster", value: "front" },
        { actionTime: 45, action: "setRotation", value: "pc" },
        { actionTime: 50, action: "blaster", value: "front" },
        { actionTime: 60, action: "setPatternTime", value: 0 },
    ],

    bossLoop: [
        { actionTime: 0, action: "setRotation", value: "pc" },
        { actionTime: 10, action: "blaster", value: "pc" },
        { actionTime: 20, action: "blaster", value: "pc" },
        { actionTime: 30, action: "blaster", value: "pc" },
        { actionTime: 35, action: "setRotation", value: "pc" },
        { actionTime: 40, action: "blaster", value: "pc" },
        { actionTime: 50, action: "blaster", value: "pc" },
        { actionTime: 60, action: "blaster", value: "pc" },
        { actionTime: 60, action: "setRotation", value: [0, 0, 0] },
        { actionTime: 65, action: "randomMoveTo", value: [-10, 10, -5, 5, 130, 160] },
        { actionTime: 85, action: "setRotation", value: "pc" },
        { actionTime: 90, action: "blaster", value: "pc" },
        { actionTime: 100, action: "blaster", value: "pc" },
        { actionTime: 110, action: "blaster", value: "pc" },
        { actionTime: 115, action: "setRotation", value: "pc" },
        { actionTime: 120, action: "blaster", value: "pc" },
        { actionTime: 130, action: "blaster", value: "pc" },
        { actionTime: 140, action: "blaster", value: "pc" },
        { actionTime: 150, action: "setRotation", value: [0, 0, 0] },
        { actionTime: 180, action: "randomMoveTo", value: [-10, 10, -5, 5, 130, 160] },
        { actionTime: 240, action: "randomMoveTo", value: [-10, 10, -5, 5, 130, 160] },
        { actionTime: 300, action: "setPatternTime", value: 0 },
    ],
    bossFinalLoop: [
        { actionTime: 0, action: "setRotation", value: [0, 0, 0] },
        { actionTime: 10, action: "blaster", value: "pc" },
        { actionTime: 20, action: "blaster", value: "pc" },
        { actionTime: 30, action: "blaster", value: "pc" },
        { actionTime: 40, action: "blaster", value: "pc" },
        { actionTime: 50, action: "blaster", value: "pc" },
        { actionTime: 60, action: "setRotation", value: [0, 0, 0] },
        { actionTime: 60, action: "moveTo", value: [0, 0, 60] },
        { actionTime: 120, action: "blaster", value: "pc" },
        { actionTime: 130, action: "blaster", value: "pc" },
        { actionTime: 140, action: "blaster", value: "pc" },
        { actionTime: 150, action: "blaster", value: "pc" },
        { actionTime: 160, action: "blaster", value: "pc" },
        { actionTime: 170, action: "blaster", value: "pc" },
        { actionTime: 180, action: "blaster", value: "pc" },
        { actionTime: 190, action: "blaster", value: "pc" },
        { actionTime: 200, action: "blaster", value: "pc" },
        { actionTime: 210, action: "blaster", value: "pc" },
        { actionTime: 220, action: "blaster", value: "pc" },
        { actionTime: 230, action: "blaster", value: "pc" },
        { actionTime: 240, action: "blaster", value: "pc" },
        { actionTime: 250, action: "blaster", value: "pc" },
        { actionTime: 260, action: "blaster", value: "pc" },
        { actionTime: 280, action: "blaster", value: "pc" },
        { actionTime: 290, action: "blaster", value: "pc" },
        { actionTime: 300, action: "blaster", value: "pc" },
        { actionTime: 310, action: "blaster", value: "pc" },
        { actionTime: 320, action: "blaster", value: "pc" },
        { actionTime: 330, action: "setRotation", value: [0, 0, 0] },
        { actionTime: 330, action: "randomMoveTo", value: [-15, 15, -5, 5, 80, 130] },
        { actionTime: 400, action: "setPatternTime", value: 0 },
    ],

};

export default npcAIPattern;