const npcBasicData = {
    baseNPCBasic: {
        npcGlb:         '../artSrc/npcShip3.glb',
        type:           'npcShip',
        collisionSize:  10,
        hp:             30,
        power:          1,
        maxSpeed:       3,
        speedAccel:     [0.1, 0.1, 0.1],
        speedDecel:     [0.9, 0.9, 0.9],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   'red',
        blasterShape:   'capsule',
        blasterRadius:  1.5,
        blasterLength:  3,
        blasterSpeed:   10,
        blasterPower:   1,
    },
    droneBasic: {
        npcGlb:         '../artSrc/npcShip1.glb',
        type:           'npcShip',
        collisionSize:  8,
        hp:             1,
        power:          1,
        maxSpeed:       3,
        speedAccel:     [0.5, 0.5, 0.5],
        speedDecel:     [0.85, 0.85, 0.85],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   'red',
        blasterShape:   'capsule',
        blasterRadius:  0.4,
        blasterLength:  2,
        blasterSpeed:   5,
        blasterPower:   1,
    },
    bomberBasic: {
        npcGlb:         '../artSrc/npcShip3.glb',
        type:           'npcShip',
        collisionSize:  10,
        hp:             5,
        power:          3,
        maxSpeed:       1,
        speedAccel:     [0.1, 0.1, 0.1],
        speedDecel:     [0.92, 0.92, 0.92],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   'violet',
        blasterShape:   'sphere',
        blasterRadius:  4,
        blasterLength:  4,
        blasterSpeed:   3,
        blasterPower:   20,
    },
    fighterBasic: {
        npcGlb:         '../artSrc/npcShip2.glb',
        type:           'npcShip',
        collisionSize:  8,
        hp:             3,
        power:          2,
        maxSpeed:       3,
        speedAccel:     [0.3, 0.3, 0.3],
        speedDecel:     [0.87, 0.87, 0.87],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   'red',
        blasterShape:   'capsule',
        blasterRadius:  0.6,
        blasterLength:  10,
        blasterSpeed:   10,
        blasterPower:   4,
    },
    destroyerBasic: {
        npcGlb:         '../artSrc/npcShip4.glb',
        type:           'npcShip',
        collisionSize:  10,
        hp:             10,
        power:          3,
        maxSpeed:       2,
        speedAccel:     [0.2, 0.2, 0.2],
        speedDecel:     [0.91, 0.91, 0.91],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   'red',
        blasterShape:   'capsule',
        blasterRadius:  0.9,
        blasterLength:  14,
        blasterSpeed:   10,
        blasterPower:   6,
    },
    cruiserBasic: {
        npcGlb:         '../artSrc/npcShip10.glb',
        type:           'npcShip',
        collisionSize:  30,
        hp:             45,
        power:          5,
        maxSpeed:       1,
        speedAccel:     [0.05, 0.05, 0.05],
        speedDecel:     [0.95, 0.95, 0.95],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   'violet',
        blasterShape:   'capsule',
        blasterRadius:  1.5,
        blasterLength:  30,
        blasterSpeed:   7,
        blasterPower:   20,
    },
    bossBasic: {
        npcGlb:         '../artSrc/npcShip100.glb',
        type:           'npcShip',
        collisionSize:  30,
        hp:             500,
        power:          10,
        maxSpeed:       1,
        speedAccel:     [0.2, 0.2, 0.2],
        speedDecel:     [0.91, 0.91, 0.91],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   'violet',
        blasterShape:   'sphere',
        blasterRadius:  4,
        blasterLength:  4,
        blasterSpeed:   4,
        blasterPower:   20,
        passable:       false,
    },
    asteroid1Basic: {
        npcGlb:         '../artSrc/asteroid1.glb',
        type:           'asteroid',
        collisionSize:  15,
        hp:             3,
        power:          10,
        defaultSpeed:   [0, 0, -9],
        rotatingSpeed:  [0, 0, 0],
    },
    asteroid2Basic: {
        npcGlb:         '../artSrc/asteroid2.glb',
        type:           'asteroid',
        collisionSize:  15,
        hp:             3,
        power:          10,
        defaultSpeed:   [0, 0, -9],
        rotatingSpeed:  [0, 0, 0],
    },
};

export default npcBasicData;