const npcBasicData = {
    baseNPCBasic: {
        npcGlb:         "artSrc/npcShip3.glb",
        type:           "npcShip",
        collisionSize:  10,
        hp:             30,
        power:          3,
        maxSpeed:       3,
        speedAccel:     [0.1, 0.1, 0.1],
        speedDecel:     [0.9, 0.9, 0.9],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   "red",
        blasterShape:   "capsule",
        blasterRadius:  1.5,
        blasterLength:  3,
        blasterSpeed:   10,
        blasterPower:   1,
        blasterSoundSrc:"soundSrc/npcBlast3.mp3",
    },
    droneBasic: {
        npcGlb:         "artSrc/npcShip1.glb",
        type:           "npcShip",
        collisionSize:  8,
        hp:             1,
        power:          3,
        maxSpeed:       3,
        speedAccel:     [0.5, 0.5, 0.5],
        speedDecel:     [0.85, 0.85, 0.85],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   "red",
        blasterShape:   "capsule",
        blasterRadius:  0.5,
        blasterLength:  2,
        blasterSpeed:   6,
        blasterPower:   1,
        blasterSoundSrc:"soundSrc/npcBlast1.mp3",
    },
    bomberBasic: {
        npcGlb:         "artSrc/npcShip3.glb",
        type:           "npcShip",
        collisionSize:  10,
        hp:             5,
        power:          7,
        maxSpeed:       1,
        speedAccel:     [0.1, 0.1, 0.1],
        speedDecel:     [0.92, 0.92, 0.92],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   "violet",
        blasterShape:   "sphere",
        blasterRadius:  4,
        blasterLength:  4,
        blasterSpeed:   3,
        blasterPower:   5,
        blasterSoundSrc:"soundSrc/npcBlast3.mp3",
    },
    fighterBasic: {
        npcGlb:         "artSrc/npcShip2.glb",
        type:           "npcShip",
        collisionSize:  8,
        hp:             3,
        power:          5,
        maxSpeed:       3,
        speedAccel:     [0.3, 0.3, 0.3],
        speedDecel:     [0.87, 0.87, 0.87],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   "red",
        blasterShape:   "capsule",
        blasterRadius:  0.7,
        blasterLength:  10,
        blasterSpeed:   9,
        blasterPower:   2,
        blasterSoundSrc:"soundSrc/npcBlast2.mp3",
    },
    destroyerBasic: {
        npcGlb:         "artSrc/npcShip4.glb",
        type:           "npcShip",
        collisionSize:  10,
        hp:             10,
        power:          7,
        maxSpeed:       2,
        speedAccel:     [0.2, 0.2, 0.2],
        speedDecel:     [0.91, 0.91, 0.91],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   "red",
        blasterShape:   "capsule",
        blasterRadius:  0.9,
        blasterLength:  14,
        blasterSpeed:   10,
        blasterPower:   3,
        blasterSoundSrc:"soundSrc/npcBlast4.mp3",
    },
    destroyerStrongerBasic: {
        npcGlb:         "artSrc/npcShip4.glb",
        type:           "npcShip",
        collisionSize:  10,
        hp:             50,
        power:          10,
        maxSpeed:       2,
        speedAccel:     [0.3, 0.3, 0.3],
        speedDecel:     [0.91, 0.91, 0.91],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   "red",
        blasterShape:   "capsule",
        blasterRadius:  0.9,
        blasterLength:  14,
        blasterSpeed:   10,
        blasterPower:   3,
        blasterSoundSrc:"soundSrc/npcBlast4.mp3",
    },
    cruiserBasic: {
        npcGlb:         "artSrc/npcShip10.glb",
        type:           "npcHeavy",
        collisionSize:  17,
        hp:             45,
        power:          20,
        maxSpeed:       1,
        speedAccel:     [0.05, 0.05, 0.05],
        speedDecel:     [0.95, 0.95, 0.95],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   "violet",
        blasterShape:   "capsule",
        blasterRadius:  1.3,
        blasterLength:  20,
        blasterSpeed:   7,
        blasterPower:   5,
        blasterSoundSrc:"soundSrc/npcBlas10.mp3",
    },
    cruiserBossBasic: {
        npcGlb:         "artSrc/npcShip10.glb",
        type:           "npcHeavy",
        collisionSize:  17,
        hp:             220,
        power:          50,
        maxSpeed:       1,
        speedAccel:     [0.05, 0.05, 0.05],
        speedDecel:     [0.95, 0.95, 0.95],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   "violet",
        blasterShape:   "capsule",
        blasterRadius:  1.3,
        blasterLength:  20,
        blasterSpeed:   7,
        blasterPower:   5,
        unpassable:     true,
        blasterSoundSrc:"soundSrc/npcBlast10.mp3",
    },
    carrierBasic: {
        npcGlb:         "artSrc/npcShip10.glb",
        type:           "npcHeavy",
        collisionSize:  17,
        hp:             500,
        power:          20,
        maxSpeed:       1,
        speedAccel:     [0.05, 0.05, 0.05],
        speedDecel:     [0.95, 0.95, 0.95],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   "violet",
        blasterShape:   "capsule",
        blasterRadius:  1.3,
        blasterLength:  20,
        blasterSpeed:   7,
        blasterPower:   5,
        blasterSoundSrc:"soundSrc/npcBlast10.mp3",
    },
    bossBasic: {
        npcGlb:         "artSrc/npcShip100.glb",
        type:           "npcHeavy",
        collisionSize:  30,
        hp:             450,
        power:          10,
        maxSpeed:       1,
        speedAccel:     [0.2, 0.2, 0.2],
        speedDecel:     [0.91, 0.91, 0.91],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   "violet",
        blasterShape:   "sphere",
        blasterRadius:  3,
        blasterLength:  3,
        blasterSpeed:   5,
        blasterPower:   7,
        unpassable:     true,
        blasterSoundSrc:"soundSrc/npcBlast3.mp3",
    },
    asteroid1FastBasic: {
        npcGlb:         "artSrc/asteroid1.glb",
        type:           "asteroid",
        collisionSize:  15,
        hp:             3,
        power:          4,
        defaultSpeed:   [0, 0, -9],
        rotatingSpeed:  [0, 0, 0],
    },
    asteroid2FastBasic: {
        npcGlb:         "artSrc/asteroid2.glb",
        type:           "asteroid",
        collisionSize:  15,
        hp:             3,
        power:          4,
        defaultSpeed:   [0, 0, -9],
        rotatingSpeed:  [0, 0, 0],
    },
    asteroid1Basic: {
        npcGlb:         "artSrc/asteroid1.glb",
        type:           "asteroid",
        collisionSize:  15,
        hp:             3,
        power:          3,
        defaultSpeed:   [0, 0, -6],
        rotatingSpeed:  [0, 0, 0],
    },
    asteroid2Basic: {
        npcGlb:         "artSrc/asteroid2.glb",
        type:           "asteroid",
        collisionSize:  15,
        hp:             3,
        power:          3,
        defaultSpeed:   [0, 0, -6],
        rotatingSpeed:  [0, 0, 0],
    },
    asteroid1SlowBasic: {
        npcGlb:         "artSrc/asteroid1.glb",
        type:           "asteroid",
        collisionSize:  15,
        hp:             3,
        power:          2,
        defaultSpeed:   [0, 0, -3],
        rotatingSpeed:  [0, 0, 0],
    },
    asteroid2SlowBasic: {
        npcGlb:         "artSrc/asteroid2.glb",
        type:           "asteroid",
        collisionSize:  15,
        hp:             3,
        power:          2,
        defaultSpeed:   [0, 0, -3],
        rotatingSpeed:  [0, 0, 0],
    },
};

export default npcBasicData;