const npcBasicData = {
    baseNPCBasic: {
        npcGlb:         '../artSrc/npcShip3.glb',
        collisionSize:  10,
        hp:             30,
        power:          1,
        maxSpeed:       3,
        speedAccel:     [0.1, 0.1, 0.1],
        speedDecel:     [0.9, 0.9, 0.9],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   'red',
        blasterShape:   'capsule',
        blasterRadius:  1.5,
        blasterLength:  3,
        blasterSpeed:   10,
        blasterPower:   1,
    },
    droneBasic: {
        npcGlb:         '../artSrc/npcShip1.glb',
        collisionSize:  7,
        hp:             1,
        power:          1,
        maxSpeed:       3,
        speedAccel:     [0.5, 0.5, 0.5],
        speedDecel:     [0.9, 0.9, 0.9],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   'red',
        blasterShape:   'capsule',
        blasterRadius:  0.4,
        blasterLength:  2,
        blasterSpeed:   5,
        blasterPower:   1,
    },
    bomberBasic: {
        npcGlb:         '../artSrc/npcShip3.glb',
        collisionSize:  10,
        hp:             5,
        power:          3,
        maxSpeed:       1,
        speedAccel:     [0.1, 0.1, 0.1],
        speedDecel:     [0.92, 0.92, 0.92],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   'violet',
        blasterShape:   'sphere',
        blasterRadius:  4,
        blasterLength:  4,
        blasterSpeed:   3,
        blasterPower:   20,
    },
    fighterBasic: {
        npcGlb:         '../artSrc/npcShip5.glb',
        collisionSize:  8,
        hp:             3,
        power:          2,
        maxSpeed:       3,
        speedAccel:     [0.3, 0.3, 0.3],
        speedDecel:     [0.9, 0.9, 0.9],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   'red',
        blasterShape:   'capsule',
        blasterRadius:  0.6,
        blasterLength:  10,
        blasterSpeed:   10,
        blasterPower:   4,
    },
    destroyerBasic: {
        npcGlb:         '../artSrc/npcShip6.glb',
        collisionSize:  10,
        hp:             10,
        power:          3,
        maxSpeed:       2,
        speedAccel:     [0.2, 0.2, 0.2],
        speedDecel:     [0.91, 0.91, 0.91],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   'red',
        blasterShape:   'capsule',
        blasterRadius:  1,
        blasterLength:  15,
        blasterSpeed:   10,
        blasterPower:   6,
    },
    cruiserBasic: {
        npcGlb:         '../artSrc/npcShip10.glb',
        collisionSize:  30,
        hp:             45,
        power:          1,
        maxSpeed:       1,
        speedAccel:     [0.05, 0.05, 0.05],
        speedDecel:     [0.95, 0.95, 0.95],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   'violet',
        blasterShape:   'capsule',
        blasterRadius:  1.5,
        blasterLength:  30,
        blasterSpeed:   7,
        blasterPower:   20,
    },
    asteroidBasic: {
        npcGlb:         '../artSrc/asteroid1.glb',
        collisionSize:  8,
        hp:             3,
        power:          5,
        maxSpeed:       5,
        speedAccel:     [1, 1, 1],
        speedDecel:     [0.9, 0.9, 0.9],
        speed:          [0, 0, 0],
        defaultSpeed:   [0, 0, 0],
        targetPosition: [],
        targetRotation: [0, 0, 0],
        blasterColor:   '',
        blasterShape:   '',
        blasterRadius:  0,
        blasterLength:  0,
        blasterSpeed:   0,
        blasterPower:   0,
    },
};

export default npcBasicData;